/** Source-controlled deployment plan. Reading this never starts or deploys a model. */
export const DEPLOYMENT_PLAN = {
  version:1,
  policy:{inference:'modal-only',deployAt:'after-local-integration',installOnMac:false,
    budget:'Existing shared ledger; no new allowance inferred',
    recovery:'Record call IDs; recover ambiguous submissions before resubmitting',
    lifecycle:'Persistent images and weight volumes; GPU containers may scale to zero'},
  services:[
    {id:'reason',existingApp:'eduworld-scene-language',source:'modal/scenesmith_language_service.py',
      adapter:'scripts/agent-world/modal_reason.py',deployment:'reuse-existing-after-live-qualification',
      roles:['intent','world-and-behaviour','spatial','terrain','review'],
      checks:['Structured output within remote token limit','Same-call recovery','Shared budget reservation and reconciliation']},
    {id:'reference',existingApp:'edworld-flux-ref',source:'modal/flux_ref_app.py',
      adapter:'scripts/agent-world/modal_generate.py',privateApp:'eduworld-agent-generation',deployment:'deployed-live-reference-generation-passed',
      checks:['Immutable PNG and request ID','Shared budget and GPU lease','One reference with shared art direction; no fallback provider']},
    {id:'object',existingApp:'edworld-trellis2-forge',source:'modal/trellis2_app.py',
      adapter:'lib/agent-world/asset-agent.ts',privateApp:'eduworld-agent-generation',deployment:'deployed-live-object-generation-and-six-view-review-passed',
      checks:['Reference checksum','Embedded textured GLB','Measured bounds and scale','Representation fits requested behaviour','Live visual inspection']},
    {id:'terrain',candidate:'https://github.com/xandergos/terrain-diffusion',
      adapter:'modal/terrain_app.py',model:'xandergos/terrain-diffusion-30m',gated:false,deployment:'deployed-native-tile-inference-passed; visual-and-domain-qualification-open',
      checks:['Pin reviewed upstream code/checkpoint and license','Verify compatible GPU and actual tensor operation',
        'Return elevation grid with physical extent and provenance','Match requested landform and scale',
        'Measure close-up detail; regional resolution is insufficient by itself','Unsupported caves and non-Earth terrain stay explicit gaps']},
  ],
  localAcceptance:['Typed plans and research evidence','Terrain planning and heightfield package contract',
    'Supported motion/particle operators and deterministic state','Checked assembly and first-person preview',
    'Checkpoint replay, privacy, budget and browser regression tests'],
  beforeStudentRelease:['Deploy and live-qualify the connected funded generation services',
    'Qualify asset selection, scale, materials and navigation on live outputs',
    'Implement and qualify missing scientific process, rig and observer-scale capabilities',
    'Pass five live scenario acceptance cases; fixture tests are insufficient',
    'Measure close-up visual quality, frame rate, memory, progress persistence and generation cost'],
  readyForStudents:false,
} as const;
